global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'taskflow-api'
    metrics_path: '/metrics'
    static_configs:
      # CHANGE THIS: Use the container name 'taskflow-api'
      - targets: ['taskflow-api:8000']